name: Deploy to Azure

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        default: ${{ github.repository }}
      azure_webapp_name:
        required: true
        type: string

jobs:
  azure:
    runs-on: ubuntu-latest
    name: Deploy to Azure
    environment:
      name: production
    needs: [build-images]

    steps:
      - name: Azure authentication
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.azure_webapp_name }}
          images: ${{ secrets.AZURE_REGISTRY_URL }}/${{ inputs.image_name }}:${{ github.sha }}