name: Run tests

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore
        run: dotnet restore
        working-directory: src

      - name: Build
        run: dotnet build --no-restore
        working-directory: src

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: src
